#!/bin/sh

#设置 luci界面语言为中文
uci set luci.main.lang=zh_cn
uci commit luci

#系统时区设置
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

#系统温度调整
uci set glfan.@globals[0].temperature='60'
uci set glfan.@globals[0].intergration='4'
uci set glfan.@globals[0].differential='20'
uci commit glfan

#设置fstab开启热插拔自动挂载
uci set fstab.@global[0].anon_mount=1
uci commit fstab

#关闭wget历史记录跟踪
echo 'hsts=0' > /root/.wgetrc

#iptables设置
sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

#无线配置
uci set wireless.radio0=wifi-device
uci set wireless.radio0.type='mac80211'
uci set wireless.radio0.path='platform/soc/c000000.wifi'
uci set wireless.radio0.band='5g'
uci set wireless.radio0.htmode='HE80'
uci set wireless.radio0.country='CN'
uci set wireless.radio0.disabled='0'
uci set wireless.radio0.channel='auto'
uci set wireless.radio0.legacy_rates='0'
uci set wireless.radio0.channels='36 40 44 48 149 153 157 161 165'
uci set wireless.radio0.hwmode='11a'
uci set wireless.default_radio0=wifi-iface
uci set wireless.default_radio0.device='radio0'
uci set wireless.default_radio0.network='lan'
uci set wireless.default_radio0.mode='ap'
uci set wireless.default_radio0.wds='1'
uci set wireless.default_radio0.isolate='0'
uci set wireless.default_radio0.hidden='0'
uci set wireless.default_radio0.disabled='0'
uci set wireless.default_radio0.ssid='GL-AXT1800-5.0G'
uci set wireless.default_radio0.encryption='sae-mixed'
uci set wireless.default_radio0.key='12345678'
uci set wireless.radio1=wifi-device
uci set wireless.radio1.type='mac80211'
uci set wireless.radio1.path='platform/soc/c000000.wifi+1'
uci set wireless.radio1.band='2g'
uci set wireless.radio1.country='CN'
uci set wireless.radio1.disabled='0'
uci set wireless.radio1.channel='auto'
uci set wireless.radio1.htmode='HE40'
uci set wireless.radio1.legacy_rates='0'
uci set wireless.radio1.noscan='1'
uci set wireless.radio1.hwmode='11g'
uci set wireless.default_radio1=wifi-iface
uci set wireless.default_radio1.device='radio1'
uci set wireless.default_radio1.network='lan'
uci set wireless.default_radio1.mode='ap'
uci set wireless.default_radio1.wds='1'
uci set wireless.default_radio1.isolate='0'
uci set wireless.default_radio1.hidden='0'
uci set wireless.default_radio1.disabled='0'
uci set wireless.default_radio1.ssid='GL-AXT1800-2.4G'
uci set wireless.default_radio1.encryption='sae-mixed'
uci set wireless.default_radio1.key='12345678'
uci set wireless.guest5g=wifi-iface
uci set wireless.guest5g.device='radio0'
uci set wireless.guest5g.network='guest'
uci set wireless.guest5g.mode='ap'
uci set wireless.guest5g.guest='1'
uci set wireless.guest5g.wds='1'
uci set wireless.guest5g.isolate='1'
uci set wireless.guest5g.disabled='1'
uci set wireless.guest5g.ssid='GL-AXT1800-5.0G-Guest'
uci set wireless.guest5g.encryption='sae-mixed'
uci set wireless.guest5g.key='00000000'
uci set wireless.guest2g=wifi-iface
uci set wireless.guest2g.device='radio1'
uci set wireless.guest2g.network='guest'
uci set wireless.guest2g.mode='ap'
uci set wireless.guest2g.guest='1'
uci set wireless.guest2g.disabled='1'
uci set wireless.guest2g.wds='1'
uci set wireless.guest2g.isolate='1'
uci set wireless.guest2g.ssid='GL-AXT1800-2.4G-Guest'
uci set wireless.guest2g.encryption='sae-mixed'
uci set wireless.guest2g.key='00000000'
uci commit wireless
sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

#AdGuardHome配置
echo 'bind_host: 0.0.0.0
bind_port: 3000
beta_bind_port: 0
users: []
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
  - 0.0.0.0
  port: 3053
  statistics_interval: 90
  querylog_enabled: true
  querylog_file_enabled: false
  querylog_interval: 2160h
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - 1.1.1.1
  - 8.8.8.8
  - 202.96.128.86
  - 202.96.134.133
  upstream_dns_file: ""
  bootstrap_dns:
  - 9.9.9.10
  - 149.112.112.10
  - 2620:fe::10
  - 2620:fe::fe:10
  all_servers: false
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
  trusted_proxies:
  - 127.0.0.0/8
  - ::1/128
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: false
  bogus_nxdomain: []
  aaaa_disabled: true
  enable_dnssec: false
  edns_client_subnet: false
  max_goroutines: 300
  ipset: []
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard DNS filter
  id: 1
- enabled: true
  url: https://adaway.org/hosts.txt
  name: AdAway Default Blocklist
  id: 2
- enabled: true
  url: https://anti-ad.net/easylist.txt
  name: anti-ad
  id: 1659348161
- enabled: true
  url: https://neodev.team/lite_adblocker
  name: lite_adblocker
  id: 1659348162
- enabled: true
  url: https://raw.githubusercontent.com/521xueweihan/GitHub520/main/hosts
  name: HelloGitHub
  id: 1659348163
whitelist_filters: []
user_rules: []
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 14' > /etc/adguardhome.yaml


echo "config AdGuardHome 'AdGuardHome'
	option httpport '3000'
	option configpath '/etc/adguardhome.yaml'
	option workdir '/etc/AdGuardHome'
	option logfile '/tmp/AdGuardHome.log'
	option verbose '0'
	option binpath '/usr/bin/AdGuardHome'
	option redirect 'dnsmasq-upstream'
	option waitonboot '1'
	option ucitracktest '1'
	option enabled '1'
	list old_redirect 'dnsmasq-upstream'
	list old_port '3053'
	list old_enabled '1'" > /etc/config/AdGuardHome
	
echo "#30 4 * * * sleep 70 && touch /etc/banner && reboot" >> /etc/crontabs/root


exit 0
